### ISSUE TITLE
can't play void enemies

### ISSUE THREAD

**Issue by Lunariuum** [WondaMegapon/Refightilization#21]
me and a friend are trying to set it up so when you die you come back as only void enemies. i've set it to have every enemy but the void ones disabled but we only spawn as lemurians. anyway to fix this?

**Comment by WondaMegapon** [comment]
Refight grabs the monster pool of the current stage and chooses from those as monsters for a player to spawn as. Since, early into the game, the monster pool does not feature Void enemies, it'll not pick them and instead go for the hardcoded, default Lemurian. I'll look into setting a monster override list in the config.

**Comment by WondaMegapon** [comment]
This is being implemented in 1.2.0.
