### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by iogeg2** [WondaMegapon/Refightilization#22]
Hello. A very good mod has a lot of settings, although a couple of very important points are missing.
1. It is necessary to be able to disable the interaction of monster teammates with boxes and all other interactables. 
2. Disable all items or at least equipment from the monster teammates (With the ability to return them on the next floor.) 
3. Respawn in the void will damage the monster teammates, although it should not.

**Comment by WondaMegapon** [comment]
1. There's already a config option to disable monster interaction with items and teleporters, and I will look into adding an additional config option to fully disable interactions for monsters.
2. This was a feature that was removed due to the instability it caused various users. I could look into it at a future point, but it will likely not be patched anytime soon.
![image](https://user-images.githubusercontent.com/18584493/158483962-b9d5a8c5-b842-4071-8a61-826179894faa.png)
3. There seems to be an inconsistency regarding how void behaves. Would you mind sending me the configuration files for Refightilization that seem to cause monsters not taking damage from being in the void?
